/* Pure decision functions for the BLE web companion's LOGIN/REGISTER flow.
 * No I/O, no locks, no BLE/storage calls - callers (sdf_ble_companion,
 * sdf_app) gather inputs (including any needed randomness - salts/nonces are
 * always generated by the caller via esp_fill_random, never in here), call
 * into here, then perform I/O based on the result. See
 * openspec/changes/add-linux-target-sdf-app-support/design.md and
 * openspec/changes/ble-companion-login-challenge-response/design.md.
 *
 * mbedtls 4.x (tf-psa-crypto) moved PBKDF2 out of its public header
 * (mbedtls/pkcs5.h no longer exists) into mbedtls/private/pkcs5.h, and hides
 * the legacy (non-PSA) mbedtls_md_hmac() declaration in the still-public
 * mbedtls/md.h behind MBEDTLS_DECLARE_PRIVATE_IDENTIFIERS. Same relocation,
 * same fix, as sdf_nuki_crypto.c - define both macros before including
 * either private header so private_access.h unlocks the real declarations
 * instead of the private_* ones. */
#define MBEDTLS_ALLOW_PRIVATE_ACCESS
#define MBEDTLS_DECLARE_PRIVATE_IDENTIFIERS
#include "sdf_services.h"

#include <string.h>

#include "mbedtls/constant_time.h"
#include "mbedtls/md.h"
#include "mbedtls/private/pkcs5.h"

esp_err_t sdf_services_web_auth_stretch_credential(
    const uint8_t *received_hash, size_t received_hash_len,
    const uint8_t salt[SDF_STORAGE_WEB_USER_SALT_LEN],
    uint32_t iteration_count,
    uint8_t stretched_credential_out[SDF_STORAGE_WEB_USER_STRETCHED_LEN]) {
  if (!received_hash || received_hash_len != SDF_STORAGE_WEB_USER_HASH_LEN ||
      !salt || !stretched_credential_out || iteration_count == 0) {
    return ESP_ERR_INVALID_ARG;
  }

  int ret = mbedtls_pkcs5_pbkdf2_hmac_ext(
      MBEDTLS_MD_SHA256, received_hash, received_hash_len, salt,
      SDF_STORAGE_WEB_USER_SALT_LEN, iteration_count,
      SDF_STORAGE_WEB_USER_STRETCHED_LEN, stretched_credential_out);
  if (ret != 0) {
    return ESP_FAIL;
  }

  return ESP_OK;
}

static esp_err_t sdf_services_web_auth_hmac_sha256(const uint8_t *key, size_t key_len,
                                                     const uint8_t *data, size_t data_len,
                                                     uint8_t out[SDF_SERVICES_WEB_AUTH_RESPONSE_LEN]) {
  const mbedtls_md_info_t *md_info = mbedtls_md_info_from_type(MBEDTLS_MD_SHA256);
  if (!md_info) {
    return ESP_FAIL;
  }

  int ret = mbedtls_md_hmac(md_info, key, key_len, data, data_len, out);
  if (ret != 0) {
    return ESP_FAIL;
  }

  return ESP_OK;
}

bool sdf_services_web_auth_verify_response(
    const uint8_t stretched_credential[SDF_STORAGE_WEB_USER_STRETCHED_LEN],
    const uint8_t *nonce, size_t nonce_len,
    const uint8_t *submitted_response, size_t response_len) {
  if (!stretched_credential || !nonce || nonce_len != SDF_SERVICES_WEB_AUTH_NONCE_LEN ||
      !submitted_response || response_len != SDF_SERVICES_WEB_AUTH_RESPONSE_LEN) {
    return false;
  }

  uint8_t expected[SDF_SERVICES_WEB_AUTH_RESPONSE_LEN];
  if (sdf_services_web_auth_hmac_sha256(stretched_credential,
                                         SDF_STORAGE_WEB_USER_STRETCHED_LEN, nonce,
                                         nonce_len, expected) != ESP_OK) {
    return false;
  }

  return mbedtls_ct_memcmp(expected, submitted_response,
                            SDF_SERVICES_WEB_AUTH_RESPONSE_LEN) == 0;
}

sdf_services_web_auth_challenge_t sdf_services_web_auth_make_login_challenge(
    const sdf_storage_web_user_t *user,
    const uint8_t nonce[SDF_SERVICES_WEB_AUTH_NONCE_LEN]) {
  sdf_services_web_auth_challenge_t challenge = {0};
  if (!user || !nonce) {
    return challenge;
  }

  memcpy(challenge.salt, user->salt, SDF_STORAGE_WEB_USER_SALT_LEN);
  challenge.iteration_count = SDF_SERVICES_WEB_AUTH_PBKDF2_ITERATIONS;
  memcpy(challenge.nonce, nonce, SDF_SERVICES_WEB_AUTH_NONCE_LEN);
  return challenge;
}

sdf_services_web_auth_challenge_t sdf_services_web_auth_make_pseudo_challenge(
    const uint8_t pseudo_salt_key[SDF_STORAGE_WEB_PSEUDO_SALT_KEY_LEN],
    const char *username,
    const uint8_t nonce[SDF_SERVICES_WEB_AUTH_NONCE_LEN]) {
  sdf_services_web_auth_challenge_t challenge = {0};
  if (!pseudo_salt_key || !username || !nonce) {
    return challenge;
  }

  /* HMAC-SHA256 output is 32 bytes; truncate to the salt length so the
   * pseudo-salt has exactly the same shape as a real per-user salt. */
  uint8_t pseudo_salt_full[SDF_SERVICES_WEB_AUTH_RESPONSE_LEN];
  if (sdf_services_web_auth_hmac_sha256(pseudo_salt_key,
                                         SDF_STORAGE_WEB_PSEUDO_SALT_KEY_LEN,
                                         (const uint8_t *)username, strlen(username),
                                         pseudo_salt_full) != ESP_OK) {
    return challenge;
  }
  memcpy(challenge.salt, pseudo_salt_full, SDF_STORAGE_WEB_USER_SALT_LEN);

  challenge.iteration_count = SDF_SERVICES_WEB_AUTH_PBKDF2_ITERATIONS;
  memcpy(challenge.nonce, nonce, SDF_SERVICES_WEB_AUTH_NONCE_LEN);
  return challenge;
}

sdf_services_web_auth_registration_decision_t sdf_services_web_auth_decide_registration(
    const char *name, const uint8_t *password_hash, size_t hash_len,
    const uint8_t salt[SDF_STORAGE_WEB_USER_SALT_LEN],
    uint16_t authorizing_user_id, bool admin_authorized,
    bool name_available) {
  sdf_services_web_auth_registration_decision_t decision = {0};
  decision.reply_authorized = admin_authorized;

  if (!admin_authorized || !name || !password_hash || !salt ||
      hash_len != SDF_STORAGE_WEB_USER_HASH_LEN) {
    return decision;
  }

  /* Refuse rather than persist an unbound credential: the alternative
   * failure mode is an account belonging to nobody, which the live
   * authority lookup would then resolve against a nonexistent user on
   * every request (companion-identity design.md "Registration refuses
   * rather than persists unbound"). The client is told the registration
   * was not granted so it never waits on a credential that was not saved. */
  if (authorizing_user_id < SDF_STORAGE_FP_USER_ID_MIN ||
      authorizing_user_id > SDF_STORAGE_FP_USER_ID_MAX) {
    decision.reply_authorized = false;
    return decision;
  }

  /* The submitted name is the user's name and the login identifier; a name
   * already held by a different enrolled user is refused with nothing
   * persisted. */
  if (!name_available) {
    decision.reply_authorized = false;
    return decision;
  }

  uint8_t stretched[SDF_STORAGE_WEB_USER_STRETCHED_LEN];
  if (sdf_services_web_auth_stretch_credential(
          password_hash, hash_len, salt, SDF_SERVICES_WEB_AUTH_PBKDF2_ITERATIONS,
          stretched) != ESP_OK) {
    return decision;
  }

  decision.should_persist = true;
  decision.user_id = authorizing_user_id;
  strncpy(decision.user.name, name, SDF_STORAGE_WEB_USER_NAME_MAX - 1);
  decision.user.name[SDF_STORAGE_WEB_USER_NAME_MAX - 1] = '\0';
  decision.user.has_credential = true;
  decision.user.valid = true;
  memcpy(decision.user.salt, salt, SDF_STORAGE_WEB_USER_SALT_LEN);
  memcpy(decision.user.stretched_credential, stretched, SDF_STORAGE_WEB_USER_STRETCHED_LEN);

  return decision;
}

bool sdf_services_web_auth_should_resolve_on_action_complete(
    sdf_services_admin_action_t action, esp_err_t result) {
  return action == SDF_SERVICES_ADMIN_ACTION_WEB_REG_AUTH && result != ESP_OK;
}

/* Same "always resolve the pending BLE client" guarantee as above, shared by
 * every BLE-triggered admin action that routes its result back to an
 * originating GATT connection: Nuki re-pair (nuki-pairing-setup-flow), and
 * Enroll-Admin / Zigbee Join (button-admin-actions-to-companion-app). Kept
 * as its own explicit, tested guard - rather than folded into the
 * WEB_REG_AUTH one above, which resolves via a different reply path
 * (sdf_ble_companion_reply_auth(), keyed by username, not conn_handle) - so
 * a future BLE-triggered action can't silently break either guarantee. */
bool sdf_services_ble_admin_action_should_resolve_on_action_complete(
    sdf_services_admin_action_t action, esp_err_t result) {
  return (action == SDF_SERVICES_ADMIN_ACTION_NUKI_REPAIR ||
          action == SDF_SERVICES_ADMIN_ACTION_ENROLL_ADMIN ||
          action == SDF_SERVICES_ADMIN_ACTION_ZB_JOIN ||
          /* Remote user-management actions resolve their requesting BLE
           * client on denial and timeout too (companion-user-mgmt). */
          action == SDF_SERVICES_ADMIN_ACTION_DELETE_USER ||
          action == SDF_SERVICES_ADMIN_ACTION_REMOTE_ENROLL) &&
         result != ESP_OK;
}
